version: "3.8"

services:
  proxy:
    image: g4f-proxy
    container_name: g4f-proxy-container
    build:
      context: .
    ports:
      - "8989:8989"
    deploy:
      resources:
        limits:
          memory: 250M
    restart: always
