name: Proxy Deploy

on:
  push:
    branches:
      - "g4f-proxy"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/projects/gpt4free-proxy
            git pull
            docker-compose -f docker-compose-proxy.yml down
            docker-compose -f docker-compose-proxy.yml build
            docker-compose -f docker-compose-proxy.yml up -d
